### PR TITLE
Data table

### PR DESCRIPTION
**Pull request by Eriken79**
This branch created two new files, InvetoryTable.js and FriendTable.js. After logging or signing in, the information of the user is routed to the profile page where it is displayed in two tables representing the inventory and friend list of the user. This rendered table is based on the information stored in the database on the backend.

### CODE REVIEW

**Comment by Eriken79** [comment]
Joseph, in LoginForm.js you have to index into loggedIn to access the JSON object, I'm not sure why that is but I saw the strange array prototype message from one of your console logs. I don't have to index into an array to render the SignUp portion so I think there's a way to gracefully refactor that.

**Comment by josephos416** [comment]
Erik why does the frontend part not pass correctly? It still runs but it isnt passing? Also the Table function only includes props for friends.

**Comment by Eriken79** [comment]
> Erik why does the frontend part not pass correctly? It still runs but it isnt passing? Also the Table function only includes props for friends.

I'm not sure, Mohamed is working on it. In reference to the props, there's two tables FriendTable and InventoryTable which access the friend prop and inventory prop respectively

**Comment by Eriken79** [comment]
> Item in an itemList needs to be a JSON object that holds item info: name of item, price, user who owns item.

Good point, I can make a new branch for that.

**Comment by Eriken79** [comment]
> Item in an itemList needs to be a JSON object that holds item info: name of item, price, user who owns item.

Made a new branch to address this, its called updateItemListSchema!

**Pull request merged**
