### PR TITLE
Jest testing

### PR DESCRIPTION
**Pull request by hannahtobiason**
Full coverage of backend accessing functions. These are the functions in user.js and userServices.js. All 12 tests pass locally, with correct database access. Next step, making sure the tests pass the CI/CD build.

Line 23 in user.js is covered by a test, however, jest doesn't know how to deal with this particular case, as it is testing for an error throw while the database is running the code, so the code gets stuck in mongoose. Approved by BJK. 

Line 24 in userServices.js does not need to be covered, as it is a connection fail, rather than a function fail. Approved by BJK.

### CODE REVIEW

**Comment by MohamedCheour98** [comment]
Thank you Hannah for making these clarifications. 

So just to be sure, are lines 23 and 24 the reasons why the backend CI Build is failing when it runs the tests or are those different issues?

**Comment by hannahtobiason** [comment]
> Thank you Hannah for making these clarifications.
> 
> So just to be sure, are lines 23 and 24 the reasons why the backend CI Build is failing when it runs the tests or are those different issues?
> 
> Also, how can we help to solve the merge conflict?

Line 23 of user.js and 24 of userServices.js are unrelated to the CI build failure. The tests pass remotely, so we have a separate issue with them not passing on the CI build.

**Comment by MohamedCheour98** [comment]
Sounds good Hannah. So if I am understanding this right, regardless of what you mentioned here, the backend build should still pass?

**Comment by hannahtobiason** [comment]
Full coverage before the most recent merge of new functionality. I think there are now two more functions that need testing. All tests pass locally, would love if everyone could verify that locally on their own machines as well. **Need to figure out why the tests time out remotely**

**Comment by Eriken79** [comment]
Hannah is the GOAT LGTM when you wanna merge it

**Pull request merged**
