### PR TITLE
Profile grocery pages

### PR DESCRIPTION
**Pull request by hannahtobiason**
Added the Grocery Page that allows users to add a new grocery run. There is a form to input an item, its price, and the owner. Users can access the New Grocery Page from a link styled as a button on their profile page. Additionally, I removed some unused functions on ProfileFunc.js, which are still accessible functions on LoginFunc.js and SignUpFunc.js.

### CODE REVIEW

**Comment by Eriken79** [comment]
fixed up the merge conflicts together in class, looks good!

**Comment by Eriken79** [comment]
The frontend should build if the Form files are refactored to only include code that's connected to the backend. @MohamedCheour98 see here for refactoring.

**Comment by josephos416** [comment]
We need to change the set person function to be more reminiscent of what we needed. It right now says setPerson but it should be setProduct

**Comment by MohamedCheour98** [comment]
I am glad you guys were able to merge successfully. Thanks Hannah for implementing the landing page of a new grocery run. Looking forward to see how it'll evolve.

**Comment by MohamedCheour98** [comment]
I did take look at the frontend build. It seems like there was an undefined function that has been used on the frontend. However, I am pretty sure that Erik took care of the problem.

**Pull request merged**
